feat: upgrade the connect state for pages
anoma/namada-interface pull request #1159
Opened 2024-10-03 20:42 UTC by euharrison

- Upgrade the connect state for pages with the `ConnectPanel` component that is similar to the `ConnectBanner` component

- Add the `useIsAuthenticated` hook to handle the previous and common case of `isConnected && hasAccount`

- Upgrade the `ExtensionLoader` to be faster providing a global atom to handle the ExtensionAttachStatus. This speed up cases where we need to show not connected states  as we don't need to run the async operation waiting the extension messages every time

2024-10-07 14:01 UTC, pedrorezende requested changes
Great work! Not approving in order to discuss a bit better the name of `useIsAuthenticated` hook, once it might lead to some confusions.

2024-10-07 18:29 UTC, euharrison commented on apps/namadillo/src/hooks/useIsAuthenticated.ts
> +export const useIsAuthenticated = (): boolean => {
@pedrorezende do you have a name suggestion?
Now we are doing both cases on this hook, checking the keychain auth + if there is an account

2024-10-07 18:36 UTC, euharrison commented on apps/namadillo/src/hooks/useConnectText.ts
hmm I'm using the `useAtomValue` that is a hook and it demands to be inside a hook. Maybe jotai has a global get function, but I feel we should avoid using if it's not strict necessary, no?

2024-10-07 18:46 UTC, euharrison commented on packages/hooks/src/useEffectSkipFirstRender.ts
This hook actually leads to buggy states, for example, the one fixed here 😬 
https://github.com/anoma/namada-interface/pull/958/files

We should be able to unsubscribe anything that is created on useEffect. I undertand that sometimes it could be more complex, but this is not the reality here 🙏 

The last use case of this utils was the `useOnNamadaExtensionAttached` and it was removed in favor of not having to request the extension attach status every time, that fixes the issue of flashing the "Connect Keychain"

https://github.com/user-attachments/assets/9640ba08-a43b-46a6-938c-c5ce8d54f8b6

2024-10-14 18:21 UTC, pedrorezende approved these changes
LGTM!

2024-10-14 18:38 UTC, merged